version: '3.7'

services:
  mosquitto:
    # mosquitto configuration
  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: always
    volumes:
      - ./containers/node-red:/data
      - ./containers/certificates:/etc/ssl/private:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "1880:1880"
